[package]
name = "rust-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
diffusionx = "0.8.2"

[dev-dependencies]
criterion = "0.8"

[[bench]]
name = "bm"
harness = false

[[bench]]
name = "random"
harness = false
