[project]
name = "python-bench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "diffusionx>=0.1.3",
    "numba>=0.62.1",
    "numpy>=2.3.5",
    "psutil>=7.1.3",
    "scipy>=1.16.3",
]
